name: Build & Upload Lambda

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies and package all Lambdas
        run: |
          cd lambda
          echo "ðŸ“¦ Packaging list_courses Lambda..."
          mkdir -p package          
          pip install -r requirements.txt -t package/
          cp handler.py package/
          cd package
          zip -r ../../list_courses.zip .
          cd ..
          rm -rf package

          echo "ðŸ“¦ Packaging create_order Lambda..."
          mkdir -p package
          pip install -r requirements.txt -t package/
          cp lambda_create_order.py package/
          cd package
          zip -r ../../create_order.zip .
          cd ..
          rm -rf lambda/package

          echo "ðŸ“¦ Packaging list_videos Lambda..."
          mkdir -p package
          pip install -r requirements.txt -t package/
          cp list_videos.py package/
          cd package
          zip -r ../../list_videos.zip .
          cd ..
          rm -rf lambda/package

          pwd
          echo "ðŸ“¦ Packaging transaction Lambda..."
          mkdir -p package
          pip install -r requirements.txt -t package/
          cp update_transaction.py package/
          cd package
          zip -r ../../update_transaction.zip .
          cd ..
          rm -rf package

          echo "ðŸ“¦ Packaging get_user_tenant Lambda..."
          mkdir -p package
          pip install -r requirements.txt -t package/
          cp get_user_tenant.py package/
          cd package
          zip -r ../../get_user_tenant.zip .
          cd ../..
          
          echo "âœ… All Lambdas packaged successfully!"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Push all Lambda zips to S3
        run: |
          aws s3 cp list_courses.zip s3://lms-infra-lambda-artifacts/lambda/list_courses.zip
          aws s3 cp create_order.zip s3://lms-infra-lambda-artifacts/lambda/create_order.zip
          aws s3 cp list_videos.zip s3://lms-infra-lambda-artifacts/lambda/list_videos.zip
          aws s3 cp update_transaction.zip s3://lms-infra-lambda-artifacts/lambda/update_transaction.zip
          aws s3 cp get_user_tenant.zip s3://lms-infra-lambda-artifacts/lambda/get_user_tenant.zip
          echo "âœ… Uploaded all Lambda packages to S3"

      - name: Update list_courses Lambda
        run: |
          aws lambda update-function-code \
            --function-name lms-infra-list-courses \
            --s3-bucket lms-infra-lambda-artifacts \
            --s3-key lambda/list_courses.zip

      - name: Update create_order Lambda
        run: |
          aws lambda update-function-code \
            --function-name lms-infra-create-order \
            --s3-bucket lms-infra-lambda-artifacts \
            --s3-key lambda/create_order.zip
          echo "âœ… Lambda lms-infra-create-order updated successfully"

      - name: List Videos Lambda
        run: |
          aws lambda update-function-code \
            --function-name lms-infra-list-videos \
            --s3-bucket lms-infra-lambda-artifacts \
            --s3-key lambda/list_videos.zip
          echo "âœ… Lambda lms-infra-list-videos updated successfully"

      - name: Update Transaction Lambda
        run: |
          aws lambda update-function-code \
            --function-name lms-infra-update-transactions \
            --s3-bucket lms-infra-lambda-artifacts \
            --s3-key lambda/update_transaction.zip
          echo "âœ… Lambda lms-infra-update-transaction updated successfully"          

      - name: Update get_user_tenant Lambda
        run: |
          aws lambda update-function-code \
            --function-name lms-infra-get-user-tenant \
            --s3-bucket lms-infra-lambda-artifacts \
            --s3-key lambda/get_user_tenant.zip
          echo "âœ… Lambda lms-infra-get-user-tenant updated successfully"
